global:
  project_path: /home/ravi.naik/learning/era/s17/s17lit
  data_path: ${global.project_path}/data
bert:
  data: ${global.data_path}/bert
  batch_size: 1024
  seq_len: 20
  embed_size: 128
  inner_ff_size: 512 # embed_size * 4
  n_heads: 8
  n_layers: 8
  n_vocab: 40000
  dropout: 0.1
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  n_workers: 4


gpt:
  data: ${global.data_path}/gpt
  batch_size: 32
  seq_len: 64
  embed_size: 768
  inner_ff_size: 3072  # embed_size * 4
  n_heads: 6
  n_layers: 6
  n_vocab: 30522
  dropout: 0.2
  lr: 3e-4
  n_workers: 4
  betas: [0.9, 0.999]
  weight_decay: 1e-4
  epochs: 2
  max_iter: 5000
  eval_inter: 500
  

vit:
  data: ${global.data_path}/vit/pizza_steak_sushi
  train_dir: ${vit.data}/train
  test_dir: ${vit.data}/test
  batch_size: 32
  img_size: 224
  embed_size: 768
  inner_ff_size: 3072
  n_heads: 6
  n_layers: 6
  n_workers: 4
  color_channels: 3
  num_classes: 10
  patch_size: 16
  lr: 3e-3
  betas: [0.9, 0.999]
  weight_decay: 0.3
  epochs: 2